### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by Skittlehub** [multiversx/mx-assets#104]

**Comment by elnicos** [comment]
Hi.
How can i do the logo.svg?
Do you have some instructions?
I cannot manage this
Thanks

**Comment by tricastor** [comment]
> Hi. How can i do the logo.svg? Do you have some instructions? I cannot manage this Thanks

Hi,
using a free tool like:
[**pngtosvg.com**](https://www.pngtosvg.com/)
works well !

**Comment by jszatanek** [comment]
Hi, 
do you know how the validate-json action is triggered ?
thx for any help !

**Comment by Ekan1402** [comment]
Buenas tardes, una pregunta, donde se han de subir los fichero para su validación? no me queda claro si se han de subir sueltos a la raiz o bien crear una carpeta con el nombre de la crypto y en cualquier caso ¡, si ha de ir dentro de alguna carpeta en concreto.

Gracias

**Comment by schimih** [comment]
Hey @Skittlehub ,
please create a new Issue with proper description of the issue that you encounter
