### ISSUE TITLE
Add Vonan logo for token VONAN-b477a6

### ISSUE THREAD

**Issue by CaPiTo26** [multiversx/mx-assets#469]
{
  "website": "https://www.vonan.app",
  "description": "The VONAN token is the official token of the vonan.app project",
  "social": {
    "email": "token@vonan.app"
  },
  "status": "active"
}
![Groupe 830](https://user-images.githubusercontent.com/24463540/169778934-a5e02c0b-1632-467a-9299-a5800f52623e.png)

![Groupe 830](https://user-images.githubusercontent.com/24463540/169778920-c0441472-917c-478d-9349-5eee2d9eac2f.svg)

**Comment by schimih** [comment]
Hello,
please create a PR here:
https://github.com/multiversx/mx-assets/pulls
