### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by BaekM2** [multiversx/mx-assets#508]
Hi, I encountered a problem, I created the token, I created the website, logo.png, logo.svg, info.json. I just don't understand how I can give "Pull request" can someone explain it to me in detail?

**Comment by Runnerstepx** [comment]
hi, you need create a fork for upload files & open PR

**Comment by BaekM2** [comment]
https://github.com/ElrondNetwork/assets/pull/509
It`s oke?

**Comment by Runnerstepx** [comment]
upload logo.png and logo.svg at in the folder when you have info.json, not in comments
