### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ihbou** [multiversx/mx-assets#556]
![caviar](https://user-images.githubusercontent.com/103725566/176940714-a8e6234c-be47-419b-8230-ed151a9a7d56.png)
![caviar](https://user-images.githubusercontent.com/103725566/176940757-71072c3e-0e97-4f24-b25c-b1e93a0e44c2.svg)

_Originally posted by @ihbou in https://github.com/ElrondNetwork/assets/pull/555#pullrequestreview-1026469067_

**Comment by schimih** [comment]
Hey @ihbou ,
please create a PR.
https://github.com/multiversx/mx-assets/pulls
Thanks!
